import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components";

// const manifaPro2 = localFont({
// 	src: "./fonts/ManifaPro2.woff",
// 	variable: "--font-manifa-pro2",
// 	weight: "100 900",
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
